# Generated by Django 4.2.13 on 2024-05-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_link', models.CharField(max_length=4000)),
                ('article_title', models.CharField(max_length=4000)),
                ('article_publish_date', models.DateField()),
                ('article_file_path', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
